### ISSUE TITLE
Show Example on How to read .ply files

### ISSUE THREAD

**Issue by ucalyptus** [centreborelli/pypotree#1]

**Comment by gfacciol** [comment]
You can use plyfile to read the vertex data from a ply file:

```
import plyfile
import numpy
pd = plyfile.PlyData.read('yourfile.ply')
xyz=numpy.vstack( [pd['vertex']['x'],  pd['vertex']['y'],  pd['vertex']['z']] ).T

```

**Comment by ucalyptus** [comment]
Thanks @gfacciol

**Comment by jiapei100** [comment]
@gfacciol 

What is the relationship between **plyfile** and **pypotree**???

**Comment by gfacciol** [comment]
plyfile writes ply files, pypotree writes potree data structures, which are
optimized for very large point clouds.
